language: ruby
rvm:
- 1.9.3
gemfile:
- Gemfile.ci
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -f d spec/
deploy:
  provider: heroku
  api_key:
    secure: fOX1K458bUbuCVBxtv8yl1Bve7dtyUySA3fpZOh2K+LroMVLfpP7+H0lqKI6DxU9ZAI8WARlICdipChmDu55a7TUf0cr41PcEI8SVD4la8Z4xzoNaWsYBKlEM55aPG0J+2a95irfeAiLpvaPm2hMehiVgIaVh5hXJZl3ZrCWxYs=
  app: oma-kx-14
  run: "rake db:migrate"
